import type { Metadata } from "next";
import "./globals.css";
import { Pixelify_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Pokeomn",
  description: "Generated by create next app",
};

const pixelifySans = Pixelify_Sans({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pixelify-sans',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pixelifySans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
